name: client
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0+1

environment:
  sdk: ^3.12.2

dependencies:
  flutter:
    sdk: flutter
  http: ^1.2.2
  path: ^1.9.0
  path_provider: ^2.1.4
  window_manager: ^0.3.7
  youtube_explode_dart: ^3.1.0
  dio: ^5.11.0
  gal: ^2.3.3

dependency_overrides:
  path_provider_foundation: 2.3.2
  path_provider_android: 2.2.10

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0
  flutter_launcher_icons: ^0.14.3

flutter:
  uses-material-design: true
  assets:
  - assets/backend/
  - assets/backend/_internal/

flutter_launcher_icons:
  android: true
  ios: true
  image_path: "assets/icon/app_icon.png"
  windows:
    generate: true
    image_path: "assets/icon/app_icon.png"
    icon_size: 256

# Nota para el futuro: 
# Para generar los iconos, asegúrate de estar en Source/client y corre:
# dart run flutter_launcher_icons
# flutter pub get